name: PR Greeting

on:
  pull_request_target:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Greet PR Author
        uses: actions/github-script@v7
        with:
          script: |
            const message = `👋 Hey @${context.payload.pull_request.user.login}!

            Thank you so much for contributing to Inspector Saab! Your contribution helps make this project better for everyone. 🎉

            While we review your PR, feel free to check out our [issues tab](${context.payload.repository.html_url}/issues) for more ways to contribute. We'd love to see more from you! 💪

            Happy coding! 🚀`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: message
            }); 